### ISSUE TITLE
Add information about VRAM address space layout

### ISSUE THREAD

**Issue by joolin1** [X16Community/x16-docs#101]
I suggest that information about the default location of the text layer and the character set is added to the table "VRAM address space layout". You can make a VPEEK, you get bits 16-9 of the address, and then you can calculate this yourself. But why not write it in the documentation directly? This is what I miss:

$1B000 - $1EBFF Default location of screen memory for text layer (layer 1) 
$1F000 - $1F7FF Default location of character set

**Comment by mooinglemur** [comment]
This information is already given here https://github.com/X16Community/x16-docs/blob/master/X16%20Reference%20-%2008%20-%20Video%20Programming.md
