### ISSUE TITLE
Combine Chapter 8 (Video) and 9 (VERA)

### ISSUE THREAD

**Issue by tomxp411** [X16Community/x16-docs#138]
Chapter 8's sole contribution is a memory map of the default VERA data layout, which can easily be folded into the VERA reference. 

I suggest we remove chapter 8 and move chapters 2-7 up by one number, then move the "Getting started" into chapter 2's spot.

**Comment by m00dawg** [comment]
Yep, agreed

**Comment by tomxp411** [comment]
ok. I'll work on that tonight.

**Comment by tomxp411** [comment]
#134

**Comment by m00dawg** [comment]
The above PR I don't think is the one the change was made in, but the current docs reflect the intent of this issue so I'm gonna go ahead and close it out.
