### ISSUE TITLE
Add note to BSOUT/CHROUT about it `cli`ing

### ISSUE THREAD

**Issue by mooinglemur** [X16Community/x16-docs#151]
BSOUT / CHROUT (and PRIMM since it calls BSOUT) will `cli` before returning.  This is legacy C64 behavior.  We should document that it does this.

C64 disasm rom addr $E6B3 @ https://www.pagetable.com/c64ref/c64disasm/ near the label `LOP2`

**Comment by DragWx** [comment]
Please do, I ran into this and it caught me off-guard when I was trying to use BSOUT to write text to the screen within a vblank ISR.

**Comment by bbmdonut** [comment]
I've been working on this - just want to wrap up one last tidbit (suggestions for workarounds), then I'll submit the PR.
