### ISSUE TITLE
Add docs for diagnostics bank

### ISSUE THREAD

**Issue by mooinglemur** [X16Community/x16-docs#155]
A long press of power (with the supporting code in a future release of the SMC) to power on will launch diags in bank #16 (#$10).

This capability depends on https://github.com/X16Community/x16-smc/pull/32 being merged and published as a release

`BANK n,16 : SYS $C000` will also start diagnostics on a working system

The behavior of the diagnostics itself will need to be mentioned in docs as well.

**Comment by JimmyDansbo** [comment]
I have started writing the documentation for the diagnostics bank. Maybe you have already seen this page https://cx16.dk/memdiag/ which I wrote before starting to merge the diagnostic ROM with official ROM?

Do you think it would be beneficial to have the technical part about how memory is tested included in the official documentation as well?

**Comment by tomxp411** [comment]
Yes, I think having the technical details would at least be interesting and can be helpful for people who would need this. So bring it. =)
